/*PARA TRABAJAR CON ESTAS CLAUSULAS, DEBEMOS DE APOYARNOS EN EL MODELO
CREADO EN EL ARCHIVO CRUD*/

/*THIS IS A NEW PRACTICE USING GROUP BY AND COUNT*/
SELECT * FROM CUENTA

INSERT INTO CUENTA (SALDO_CUENTA, FECHA_CREACION, FECHA_EXPIRACION, NOMBRE_TITULAR)
	VALUES
	(1000.00, '10-02-2020', '31-12-2025','RENE CEVALLOS'),
	(500.00, '12-02-2020', '01-12-2025','CARLOS AVILA'),
	(800.00, '05-02-2020', '10-12-2025','STEFANIA MUÑOZ'),
	(1000.00, '03-02-2020', '08-12-2025','DAYANNA DELGADO');

SELECT SALDO_CUENTA, COUNT(*) FROM CUENTA GROUP BY SALDO_CUENTA;

SELECT SALDO_CUENTA, COUNT(*) AS CANTIDAD_CEV FROM CUENTA
	WHERE SALDO_CUENTA >=500
	GROUP BY SALDO_CUENTA
/*GROUP BY CON MAS DE UN DATO DE ENTRADA*/
SELECT SALDO_CUENTA, NOMBRE_TITULAR, COUNT(*) AS CANTIDADES FROM CUENTA
	GROUP BY SALDO_CUENTA, NOMBRE_TITULAR

/*SALDO MAYOR EN LA CONSULTA*/
SELECT SALDO_CUENTA, NOMBRE_TITULAR,
	MAX(SALDO_CUENTA) AS SALDO_MAXIMO FROM CUENTA
		GROUP BY SALDO_CUENTA, NOMBRE_TITULAR

/*PODEMOS USAR LA CLAUSULA BETWEEN PARA PODER VER LOS VALORES
DE UN DATO QUE SE ENCUENTRE EN CIERTO RANGO*/
SELECT SALDO_CUENTA, NOMBRE_TITULAR, 
	MIN(SALDO_CUENTA) AS SALDO_MINIMO 
		FROM CUENTA
		WHERE SALDO_CUENTA BETWEEN 500.00 AND 800.00
	GROUP BY 
		SALDO_CUENTA, NOMBRE_TITULAR