
/*this is a simple crud with postgressql*/
CREATE TABLE CUENTA (
	ID_CUENTA serial,
    SALDO_CUENTA decimal,
	FECHA_CREACION date, 
	FECHA_EXPIRACION date,
	NOMBRE_TITULAR varchar,
	PRIMARY KEY (ID_CUENTA)
)
INSERT INTO CUENTA 
	(SALDO_CUENTA, FECHA_CREACION, FECHA_EXPIRACION, NOMBRE_TITULAR)
VALUES
	(200.00, '10-02-2022', '20-02-2025', 'Alexis López'),
	(1000.00, '25-10-2021', '20-03-2025', 'Karen Almeida'),
	(300.00, '30-04-2020', '31-12-2028', 'Jhony Larrea')
	
/*consultamos todos los datos*/
SELECT * FROM CUENTA;

/*consultamos solo un grupo de datos*/

SELECT NOMBRE_TITULAR FROM CUENTA WHERE SALDO_CUENTA>200;

/*actualizamos todos los datos de golpe*/
UPDATE CUENTA SET NOMBRE_TITULAR = 'RENEGADO';

/*ACTUALIZAMOS LOS DATOS EN BASE A UN DATO ESPECIFICO*/

UPDATE CUENTA SET NOMBRE_TITULAR = 'Alexis López' WHERE SALDO_CUENTA = '200.00';


/*ESTO NO ES RECOMENDABLE EN NINGUN SENTIDO*/
DELETE FROM CUENTA;
/*ESTO ES LO MAS RECOMENDABLE, ELIMINAR UN DATO O SERIE DE DATOS EN BASE A
ALGUN CAMPO ESPECIFICO*/

DELETE FROM CUENTA WHERE SALDO_CUENTA ='300.00' AND NOMBRE_TITULAR ='RENEGADO';